### ISSUE TITLE
com.lalongooo.videocompressor.video.MediaController.convertVideoFrame

### ISSUE THREAD

**Issue by srinivaskrify** [lalongooo/VideoCompressor#2]
Hi,

Got this issue with api level 17 and below so at point of code app is calling for "convertVideoFrame" native method in MediaController.class.( Its working prefect for above api 17).

I debugged further and found that in jni package "video.c" file JNI function declaration is wrong (which should involve running app package name but I found something else) .

And calling MediaController.getInstance() from AsycTask I think even over there static native method "convertVideoFrame" wont get called. 

Please check it once :)

**Comment by lalongooo** [comment]
Hi @srinivaskrify, there are some constraints using this example in certain android versions. It seems like it only works for API 17+. This information is available in the Telegram for Android source code, I'll take a look and will update the README to avoid issues like this.

Thanks!

**Comment by srinivaskrify** [comment]
Sure Jorge. Only issue I found was app cant able to call native method if
you solve that issue it will be prefect.

Thanks!

On Wed, Nov 11, 2015 at 9:44 PM, Jorge E. Hernández <
notifications@github.com> wrote:

> Hi @srinivaskrify <https://github.com/srinivaskrify>, there are some
> constraints using this example in certain android versions. It seems like
> it only works for API 17+. This information is available in the Telegram
> for Android source code, I'll take a look and will update the README to
> avoid issues like this.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lalongooo/VideoCompressor/issues/2#issuecomment-155831075>
> .
>



-- 
Thanks & Regards,
Srinivas
Team Coordinator
•Mail: srinivas@krify.net
•Web: http://www.krify.com/
•(US)   212-380-1160
•(UK)   020-3002-0454
•(India) 0884-2342100 Ex 24
