### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zapl** [lalongooo/VideoCompressor#21]
I am not a lawyer and not even sure how to do it correctly but I'm pretty sure you're not allowed to put an MIT license around GPL'd code like that. See http://programmers.stackexchange.com/questions/234026/forking-gpl-project-do-i-have-full-rights-on-the-new-fork-or-still-dependencies and http://programmers.stackexchange.com/questions/193565/changing-the-license-in-a-fork-from-gpl-to-gpl-compatible

**Comment by lalongooo** [comment]
Wooops! Definitely you are correct!

Please see e8edb381ecc7f35419bf399eb917bc4c59f2d188

I just added a licence via http://www.addalicense.com/ to fix this issue https://github.com/lalongooo/VideoCompressor/issues/15.

Now it's fixed.

Thank you very much.
