### ISSUE TITLE
Getting issue on Samsung Note 3 Neo

### ISSUE THREAD

**Issue by gurpreet-clickapps** [lalongooo/VideoCompressor#26]
Error 0xfffffc03

**Comment by lalongooo** [comment]
Any error messages? Logcat? Have you tried what's in the [README](https://github.com/lalongooo/VideoCompressor/blob/master/README.md)?

**Comment by gurpreet-clickapps** [comment]
@lalongooo 
After R&D i found that:- 
Issue was due to media Player instance.
I found solution for the issue that i have reset my media player before starting video compressor.
