### ISSUE TITLE
start video compression error

### ISSUE THREAD

**Issue by kuronaru** [lalongooo/VideoCompressor#3]
I encountered this error, please help me:

what's the file size limit? coz i'm trying to compress about 700MB file size

    11-11 18:59:06.111 9054-9054/com.lalongooo.videocompressor D/MainActivity: Start video compression
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime: Process: com.lalongooo.videocompressor, PID: 9054
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:309)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:  Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at android.media.MediaMetadataRetriever.setDataSource(Native Method)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at com.lalongooo.videocompressor.video.MediaController.convertVideo(MediaController.java:228)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at    com.lalongooo.videocompressor.MainActivity$VideoCompressor.doInBackground(MainActivity.java:124)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at com.lalongooo.videocompressor.MainActivity$VideoCompressor.doInBackground(MainActivity.java:113)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    11-11 18:59:06.134 9054-9540/com.lalongooo.videocompressor E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818) 
    11-11 18:59:06.382 9054-9099/com.lalongooo.videocompressor E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb3aed870

**Comment by lalongooo** [comment]
AFAIK 700mb should be possible to compress using this example. But you should consider the specs of the device/emulator you're testing on.
Also, please take a look to https://github.com/lalongooo/VideoCompressor/issues/2, are you trying with android API 17+?

**Comment by kuronaru** [comment]
@lalongooo yup, i'm using Nexus 5 with MarshMallow now

**Comment by lalongooo** [comment]
Mmmmm....hard to know if it works properly on Marshmallow, no tested yet. As mentioned in the README, this example is based in the Telegram for Android app. So, if Telegram works properly on Marshmallow, this example should work too.
