### ISSUE TITLE
Not able to import isoparser-1.0.6 jar

### ISSUE THREAD

**Issue by RudreshJR** [lalongooo/VideoCompressor#32]
com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK builddef.lst
	File1: F:\Zikrabyte\viraltube_new\sample_compression\app\libs\isoparser-1.0.6.jar
	File2: C:\Users\Rudresh\.gradle\caches\modules-2\files-2.1\com.googlecode.mp4parser\isoparser\1.1.20\44b7ee9785227a29db4048ee36758ffa553b749e\isoparser-1.1.20.jar

Can u please tell me how to solve this error

**Comment by lalongooo** [comment]
This is not related to the project, it is related to a conflict with your dependencies.
