### ISSUE TITLE
Can't find the compressed file

### ISSUE THREAD

**Issue by fabiocarballo** [lalongooo/VideoCompressor#7]
Hello, 

I'm using your app but when I select a file and compress it don't know where to find it.

I looked in the source code and it seems that is not saving it anywhere. Am I wrong?

Thank you

**Comment by lalongooo** [comment]
Here... https://github.com/lalongooo/VideoCompressor/blob/master/app/src/main/java/com/lalongooo/videocompressor/video/MediaController.java#L246

**Comment by fabiocarballo** [comment]
Sorry, you are right.
